# Inspiration for this Dockerfile came from:
# https://devblogs.microsoft.com/cppblog/c-development-with-docker-containers-in-visual-studio-code/
FROM debian

RUN apt -y update && apt -y install
RUN apt -y install gcc valgrind vim make git

RUN useradd -s /bin/bash -m vscode \
 && groupadd docker \
 && usermod -aG docker vscode

USER vscode

